#!/bin/sh
# Provides: SeedSigner 
# Description: Start SeedSigner main.py

start() {
    # Enable kernel modules
    modprobe bcm2708_fb
    modprobe aes_arm
    modprobe aes_generic
    modprobe cmac
    modprobe bnep
    modprobe hci_uart
    modprobe btbcm
    modprobe bluetooth
    modprobe ecdh_generic
    modprobe ecc
    modprobe libaes
    modprobe spidev
    modprobe 8021q
    modprobe garp
    modprobe stp
    modprobe llc
    modprobe brcmfmac
    modprobe brcmutil
    modprobe sha256_generic
    modprobe libsha256
    modprobe cfg80211
    modprobe raspberrypi_hwmon
    modprobe rfkill
    modprobe bcm2835_codec
    modprobe v4l2_mem2mem
    modprobe bcm2835_isp
    modprobe bcm2835_v4l2
    modprobe snd_bcm2835
    modprobe bcm2835_mmal_vchiq
    modprobe videobuf2_dma_contig
    modprobe videobuf2_vmalloc
    modprobe videobuf2_memops
    modprobe videobuf2_v4l2
    modprobe spi_bcm2835
    modprobe videobuf2_common
    modprobe snd_pcm
    modprobe snd_timer
    modprobe snd
    modprobe videodev
    modprobe mc
    modprobe vc_sm_cma
    modprobe fixed
    modprobe uio_pdrv_genirq
    modprobe uio
    modprobe ip_tables
    modprobe x_tables
    modprobe ipv6
    modprobe spidev
    modprobe spi-bcm2835
    
    # Go to the SeedSigner directory and run SeedSigner 
    python3 /opt/src/main.py &
    echo "Service starting up"   
}

stop () {    
    echo "Service shutting down"
}

status () {
    echo "Everything looks good"
}

##case statement to be used to call functions##
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status 
        ;;
    *)
        echo $"Usage: $0 {start|stop|status}"
        exit 5
esac
exit $?
