#!/bin/bash


# Variables

current_dir="$(pwd)"
custom_rootfs="../rpi-seedsigner/board/raspberrypi/rootfs-overlay"
defconfig_dir="../rpi-seedsigner/configs/rpi-seedsigner_defconfig"
random_password=$(cat /dev/urandom | tr -dc [a-zA-Z0-9-.,_@%] | head -c 20)
seedsigner_sw="https://github.com/SeedSigner/seedsigner.git"

# Functions

build_image() {
    # If Makefile is not in current directory
    if [ ! -f $current_dir/Makefile ]; then
        
        # Clean directory 
        find $current_dir -type f ! -name ".gitignore" ! -name "builder" -delete
        find $current_dir -empty -type d -delete
        
        # Setup external tree
        make BR2_EXTERNAL=../rpi-seedsigner/ O=$current_dir -C ../buildroot/ 2> /dev/null > /dev/null
        
        if [ ! -f $custom_rootfs/opt/ ]; then
            # Download SeedSigner from GitHub and put into rootfs
            git clone -b "0.5.1-ram" $seedsigner_sw $custom_rootfs/opt/
                
            # Delete unnecessary files to save space
            rm -rf $custom_rootfs/opt/.git 
            rm -rf $custom_rootfs/opt/.gitignore
            rm -rf $custom_rootfs/opt/requirements.txt 
            rm -rf $custom_rootfs/opt/docs
            rm -rf $custom_rootfs/opt/README.md 
            rm -rf $custom_rootfs/opt/LICENSE.md
            rm -rf $custom_rootfs/opt/enclosures
            rm -rf $custom_rootfs/opt/seedsigner_pubkey.gpg 
            rm -rf $custom_rootfs/opt/setup.py
        fi      
    fi
    # Make the defconfig
    make rpi-seedsigner_defconfig
    # Make the image
    make
}





while getopts 'iph' OPTION; do
    case "$OPTION" in
    i)
        if [ -z $2 ]; then
        # Replace root password
        sed -i "13s/.*/BR2_TARGET_GENERIC_ROOT_PASSWD="\"$random_password\""/" $defconfig_dir
        build_image  
        
        elif [ $2 == "root" ]; then
        # Ask for a password
        read -s -p "Type Password: " root_password
        # Replace root password
        sed -i "13s/.*/BR2_TARGET_GENERIC_ROOT_PASSWD="\"$root_password\""/" $defconfig_dir
        build_image 
        
        fi
      ;;
    h)
echo -e "Help menu:

./build -i          [Build SeedSigner OS | Random root password]
./build -i root     [Build SeedSigner OS | Custom root password]"
      ;;
  esac
done


exit 0


