#!/bin/bash


# Variables

current_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
random_password=$(cat /dev/urandom | tr -dc [a-zA-Z0-9-.,_@%] | head -c 20)
seedsigner_app="https://github.com/SeedSigner/seedsigner.git"

user_dir="../rpi-seedsigner"
user_rootfs=$user_dir"/board/raspberrypi/rootfs-overlay"
user_defconfig=$user_dir"/configs/rpi-seedsigner_defconfig"

dev_dir="../rpi-seedsigner-dev"
dev_rootfs=$dev_dir"/board/raspberrypi/rootfs-overlay"
dev_defconfig=$dev_dir"/configs/rpi-seedsigner-dev_defconfig"

# Functions

build_user_image() {
    # If Makefile is not in current directory
    if [ ! -f $current_dir/Makefile ]; then
        
        # Clean directory 
        find $current_dir -type f ! -name ".gitignore" ! -name "builder" -delete
        find $current_dir -empty -type d -delete
        
        # Setup external tree
        make BR2_EXTERNAL=../rpi-seedsigner/ O=$current_dir -C ../buildroot/ 2> /dev/null > /dev/null
        
        if [ ! -f $user_rootfs/opt/ ]; then
            # Download SeedSigner from GitHub and put into rootfs
            git clone -b "0.5.1-ram" $seedsigner_app $user_rootfs/opt/
                
            # Delete unnecessary files to save space
            rm -rf $user_rootfs/opt/.git 
            rm -rf $user_rootfs/opt/.gitignore
            rm -rf $user_rootfs/opt/requirements.txt 
            rm -rf $user_rootfs/opt/docs
            rm -rf $user_rootfs/opt/README.md 
            rm -rf $user_rootfs/opt/LICENSE.md
            rm -rf $user_rootfs/opt/enclosures
            rm -rf $user_rootfs/opt/seedsigner_pubkey.gpg 
            rm -rf $user_rootfs/opt/setup.py
        fi      
    fi
    # Make the defconfig
    make rpi-seedsigner_defconfig
    # Make the image
    make
}


build_dev_image() {
    # If Makefile is not in current directory
    if [ ! -f $current_dir/Makefile ]; then
        
        # Clean directory 
        find $current_dir -type f ! -name ".gitignore" ! -name "builder" -delete
        find $current_dir -empty -type d -delete
        
        # Setup external tree
        make BR2_EXTERNAL=../rpi-seedsigner-dev/ O=$current_dir -C ../buildroot/ 2> /dev/null > /dev/null
        
        if [ ! -f $dev_rootfs/opt/ ]; then
            # Download SeedSigner from GitHub and put into rootfs
            git clone -b "0.5.1-ram" $seedsigner_app $dev_rootfs/opt/
                
            # Delete unnecessary files to save space
            rm -rf $dev_rootfs/opt/.git 
            rm -rf $dev_rootfs/opt/.gitignore
            rm -rf $dev_rootfs/opt/requirements.txt 
            rm -rf $dev_rootfs/opt/docs
            rm -rf $dev_rootfs/opt/README.md 
            rm -rf $dev_rootfs/opt/LICENSE.md
            rm -rf $dev_rootfs/opt/enclosures
            rm -rf $dev_rootfs/opt/seedsigner_pubkey.gpg 
            rm -rf $dev_rootfs/opt/setup.py
        fi      
    fi
    # Make the defconfig
    make rpi-seedsigner-dev_defconfig
    # Make the image
    make
}

while getopts 'iph' OPTION; do
    case "$OPTION" in
    i)
        if [ -z $2 ]; then
        # Replace root password
        sed -i "12s/.*/BR2_TARGET_GENERIC_ROOT_PASSWD="\"$random_password\""/" $user_defconfig

        build_user_image  
        
        elif [ $2 == "root" ]; then
        # Ask for a password
        read -s -p "Type Password: " root_password
        # Replace root password
        sed -i "12s/.*/BR2_TARGET_GENERIC_ROOT_PASSWD="\"$root_password\""/" $user_defconfig

        build_user_image 
                
        elif [ $2 == "dev" ]; then
        # Ask for a password
        read -s -p "Type Password: " root_password
        # Replace root password
        sed -i "12s/.*/BR2_TARGET_GENERIC_ROOT_PASSWD="\"$root_password\""/" $dev_defconfig
        build_dev_image 
 
        fi
      ;;
    h)
echo -e "Help menu:

./builder -i          [Build SeedSigner OS | Random root password]
./builder -i root     [Build SeedSigner OS | Custom root password]
./builder -i dev      [Build SeedSigner OS Developer version | Custom root password]" 
      ;;
  esac
done


exit 0


